::cant::can't
::couldnt::couldn't
::darent::daren't
::dont::don't
::havent::haven't
::hed::he'd
::hes::he's
::id::I'd
::im::I'm
::isnt::isn't
::ive::I've
::neednt::needn't
::shes::she's
::theyd::they'd
::theyre::they're
::theyve::they've
::weve::we've
::wont::won't
::wouldnt::wouldn't
::youd::you'd
::youre::you're
::youve::you've